### ISSUE TITLE
Connector Error, plus

### ISSUE THREAD

**Issue by ostracizado** [luuuis/hass_wibeee#65] opened 2023-07-22 17:58 UTC
The response-time is wonderful, but still the connection problems persiste:
```
This error originated from a custom integration.

Logger: custom_components.wibeee.api
Source: custom_components/wibeee/api.py:31
Integration: wibeee (documentation, issues)
First occurred: 21 July 2023 at 21:41:26 (258 occurrences)
Last logged: 18:50:21

Error getting http://192.168.2.139/services/user/devices.xml after 5 retries: ClientConnectorError: Cannot connect to host 192.168.2.139:80 ssl:default [Connect call failed ('192.168.2.139', 80)]
```
And I tried to solve it with some automations and reloads of integration/entities.

But a new one has been added:

```
Logger: homeassistant.components.sensor
Source: custom_components/wibeee/api.py:32
Integration: Sensor (documentation, issues)
First occurred: 21 July 2023 at 21:41:26 (258 occurrences)
Last logged: 18:50:21

Error while setting up wibeee platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wibeee/sensor.py", line 206, in async_setup_entry
    device = await api.async_fetch_device_info(retries=5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wibeee/api.py", line 32, in async_fetch_device_info
    device_id = devices['devices']['id']
                ~~~~~~~^^^^^^^^^^^
KeyError: 'devices'
```

Any ideas, @luuuis?

Ps. "258 occurrences", in both cases... that's a lot.

**Comment by luuuis** [comment] 2023-07-24 07:44
This looks like a duplicate of #52.

I am aware that Wibeee device sometimes does not respond. It is not a problem in the integration and there's not much that can be done in the integration except to avoid connecting to the device. It's a fault in Wibeee devices.

**Closed** 2023-09-25 12:41 UTC
Labels: duplicate, wibeee wtfs
