### ISSUE TITLE
Inestability of entities availability

### ISSUE THREAD

**Issue by TecoolVa2** [luuuis/hass_wibeee#29] opened 2022-01-07 09:26 UTC
Hi, the integration worked fine although it was hard to get the conection to the device (mirubee box v2) the first time, but from time to time I lose the availability of the related entities... However the mobile APP wibeee works continuesly without problem.
I don't have idea about the reason, I was thinking that the wifi connection to the device is not good, indeed is far from the router, bu
![Captura](https://user-images.githubusercontent.com/76661180/148522601-d0de08a4-3b8b-47ec-a016-57a824a2d1f7.JPG)
t not much.... however the APP aplication in my mobile is always receiving data and the raspberry not... Any idea?

**Comment by luuuis** [comment] 2022-01-07 09:52
Hi @TecoolVa2 , this is normally caused by the device returning invalid responses or not responding. If you go into HA logs do you have any errors related to wibeee?

[![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/)

The problem is that the device sends information up to Wibeee servers every 60 seconds but with this integration we are (by default) polling every 15 seconds and sometimes the device is not able to handle it. The device's API is in fact very unreliable and the integration has to do a lot of work to try to work around that.

For myself and other users 15s has been found to be stable but one workaround you can try is increasing the polling interval in the integration configuration.

![Configuration - Home Assistant 2022-01-07 09-49-22](https://user-images.githubusercontent.com/161006/148525706-387667d5-787c-43e2-9116-c4199d7b4624.jpg)

**Comment by luuuis** [comment] 2022-01-07 09:53
One other thing. In my experience it seems that the device becomes more reliable after it has been power cycled. It is not enough to reboot from the device's web UI, an actual power cycle is needed.

**Comment by t3lmoazevedo** [comment] 2022-01-07 11:25
Is there a way to retry the connection after the device looses connectivity?
One of my devices ent offline for some hours and it doesnt update anymore when it connects. I have to restart HA for that.

![image](https://user-images.githubusercontent.com/41584793/148537151-4fe9046b-2c3a-442a-b9c8-4afed5ba5d4b.png)

![image](https://user-images.githubusercontent.com/41584793/148537208-e60be826-2217-4309-876a-5a400e94c28a.png)

**Comment by TecoolVa2** [comment] 2022-01-07 16:02
Thanks for the answer! In my case I believe that the device configuration could be the cause of it. It is a Mirubee Box v2. I tried to update the firmware but always fails... Changing the interval there is no positive effect....

**Comment by luuuis** [comment] 2022-01-07 16:24
@TecoolVa2 I have a Mirubox V2 as well and it's working fine at 15s scan interval. Can you go into HA logs and copy the output from the wibeee component into here? Perhaps there is something else at play.

@t3lmoazevedo retries are already in use so I'd be curious to know what is happening in your situation. Can you open a new issue and also include the logs in there from around the time when the device is first online and then goes offline?

**Comment by luuuis** [comment] 2022-01-10 17:33
Can you open the following in your web browser and paste here the contents of each URL?

http://192.168.1.44/services/user/devices.xml
http://192.168.1.44/en/status.xml

**Comment by TecoolVa2** [comment] 2022-01-10 18:23
I can when the integrations works.... when it doesn't work like now, I can't open them.  I attach here the status.xml which I took last Friday when the integration was working...
[wibee.txt](https://github.com/luuuis/hass_wibeee/files/7841073/wibee.txt)

**Comment by luuuis** [comment] 2022-01-10 18:43
Right, if you can not get the status then the integration is also not able to.

1. What are you using as the scan interval in the integration configuration?
2. Do you have another integration maybe also using the API? I've learned that you have to be very gentle with the API or the device will hang.
3. Have you tried to shut off the power of the Wibeee and then back on again?

**Comment by TecoolVa2** [comment] 2022-01-10 22:12
Thanks Luis...
I looked at the device now and it is burnt... Leds are off...bad luck,,,, Failed yesterday at 20.15 when I realised about the lack of signal.....I believe that it was the same problema as before but now it is dead...  I don't if the times before was starting to fail but now seems to be definitive.... :(
![9 Jan 2021](https://user-images.githubusercontent.com/76661180/148847150-baf9c500-89fa-48bd-b505-db544e955736.JPG)

**Comment by luuuis** [comment] 2022-01-11 13:56
Thanks for updating and sorry to hear about your dead Mirubox. I will close this issue as it seems the integration was working well in this case.

**Closed by luuuis** 2022-01-11 13:56 UTC
