### ISSUE TITLE
Sensor reports stale data instead of "unavailable"

### ISSUE THREAD

**Issue by antonio-fiol** [luuuis/hass_wibeee#74] opened 2024-01-08 07:59 UTC
Under circumstances I don't quite understand, sometimes HA shows stale (constant) data, for nearly a whole hour, rather than the sensors becoming unavailable.
![image](https://github.com/luuuis/hass_wibeee/assets/23309681/7c76eb0d-89a5-426c-b2d2-916b91668e48)

**Comment by luuuis** [comment] 2024-01-08 10:56
Please enable debug logs for the integration until the problem occurs. Once it happens, disable debug logging and send the downloaded file to cheery.key9586@fastmail.com.

https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics

**Comment by antonio-fiol** [comment] 2024-01-08 11:37
Enabled and waiting. Thank you!!!

**Comment by antonio-fiol** [comment] 2024-01-08 13:27
It did something similar (possibly not exactly the same as it was just for a couple of minutes) and I just shared the logs. I enabled debug logging again and will wait for a longer occurrence.

**Comment by luuuis** [comment] 2024-01-08 14:02
@antonio-fiol the log looks more or less normal. There are some timeouts and bad responses (normal for Wibeee) that cause updates to get delayed for some time.

```
2024-01-08 14:08:44.909 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <entity sensor.wibeee_ababababababa_capacitive_reactive_energy_l4=193>
2024-01-08 14:08:49.381 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. TimeoutError: 
2024-01-08 14:08:49.381 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.800s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:08:57.381 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. TimeoutError: 
2024-01-08 14:08:57.381 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:09:00.382 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml after 3 retries: TimeoutError: 
2024-01-08 14:09:08.380 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. TimeoutError: 
2024-01-08 14:09:08.381 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.400s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:09:12.381 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. TimeoutError: 
2024-01-08 14:09:12.381 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:09:16.559 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. ServerDisconnectedError: Server disconnected
2024-01-08 14:09:16.559 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.400s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:09:17.219 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://1.2.3.4/en/status.xml, will retry. ClientResponseError: 400, message="Expected HTTP/:\n\n  b'AT+CIPSENDBUF=4,322'\n    ^", url=URL('http://1.2.3.4/en/status.xml')
2024-01-08 14:09:17.219 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.800s to retry http://1.2.3.4/en/status.xml...
2024-01-08 14:09:19.331 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://1.2.3.4/en/status.xml: <response>
2024-01-08 14:09:19.332 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <entity sensor.wibeee_ababababababa_phase_voltage_l1=228.90>
```

I am not sure of the time when your problem occurred so next time please send also a screenshot or indicate the date and time so I know where to look in the logs.

One more thing. It looks like you have the polling interval configured to 15 seconds? This will cause too much load on the meter and may be the cause for all your errors. If you need high resolution data I recommend [configuring Local Push](https://github.com/luuuis/hass_wibeee/?tab=readme-ov-file#configuring-local-push-optional-advanced) and then setting the polling interval to a much higher value (minutes).

High polling interval with Local Push will keep the Wibeee stable while you still receive high frequency updates (same frequency that is sent to  Wibeee Nest). In my installation I have polling configured for every 30 minutes and sensors still update every few seconds through Local Push.

<img src="https://github.com/luuuis/hass_wibeee/assets/161006/bc7635c4-7669-44cb-b377-2a797c3e3e60" width="300" /> 
<img src="https://github.com/luuuis/hass_wibeee/assets/161006/8f4e6f9d-e70f-49bb-87f1-5f07acdef891" width="400" />

Please note I am considering making this kind of setup mandatory in future versions (poll interval every 1 minute and not configurable).

**Comment by antonio-fiol** [comment] 2024-01-09 22:34
Noted, and will try as soon as I can.
I did not change anything in the configuration yet.
Meanwhile please see the log I sent if you can.
Today approx 13:30 to 14:20 the reading was flat, and that happened again at 19:30 to 20:20.

**Comment by luuuis** [comment] 2024-01-09 23:21
@antonio-fiol looking through the logs that you have sent there are what seem to be many failures to connect to Wibeee. The errors are a bit different from the common ones (like in your previous log) but the cause is likely to be that Wibeee is overloaded by your polling every 15 seconds and not accepting connections at that point.

```
2024-01-09 13:26:41.538 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:26:47.678 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:26:50.749 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:27:03.037 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:27:19.677 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:27:32.157 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:27:49.693 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:28:02.173 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:28:19.709 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
2024-01-09 13:28:32.189 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.68.140/en/status.xml after 3 retries: ClientConnectorError: Cannot connect to host 192.168.68.140:80 ssl:default [Connect call failed ('192.168.68.140', 80)]
```

This is assuming there is nothing wrong with your network/environment, which would be beyond my control. If you are comfortable using the HA console or ssh you could try to enter the homeassistant docker container and see if you are able to connect to Wibeee.

```bash
ha > login
# docker exec -it homeassistant bash
homeassistant:/config# curl http://192.168.68.140/en/status.xml
```

I would expect you to not be able to get a response using `curl` while the errors are occurring.

PS I would expect the sensor values to be missing (unavailable) rather than flat so that is something to maybe look into.

**Comment by luuuis** [comment] 2024-01-10 13:27
My experience has been that the device became very slow to respond to the Web UI at some point. This was not the case when I originally installed it in 2018 and I suspect it is a hardware issue that manifests with age (I did not upgrade the firmware for years).

> I don't know if there's any correlation with the time when it failed, but I've observed that the lights pattern in the device sometimes change (to red blinking, blue OFF), which I understand means "disconnected".

If Wibeee Nest is unresponsive for some reason then the device will start to save data locally so that it can upload later. I have found that during this time the Web interface (and therefore `status.xml`) becomes unresponsive. Maybe that is the cause of your problem? It could come down to networking issues.

Using Local Push with HA improves this aspect also: assuming your HA has good availability then Wibeee should be able to always push data to HA.

I will try to reproduce this case locally to see why the sensor is not becoming unavailable.

**Comment by antonio-fiol** [comment] 2024-01-10 15:47
I had the chance to quickly look into the current configuration of my wibeee device. It uses this Server configuration:
![image](https://github.com/luuuis/hass_wibeee/assets/23309681/673b2398-7dc8-4ee1-ba34-bc0e2392fa17)

I don't see that as an option on the list of cloud services to relay the data to.
I understood that, to keep Iberdrola's app working, I should "move" that server and port setting to somewhere in HA, and HA would forward all measurements to the same server, in a "transparent" way.

I must be missing something... :-(

**Comment by luuuis** [comment] 2024-01-10 17:20
I believe that `ingest-prod-iberdrola.wibeee.com` and the hostname used in the integration, `datosmonitorconsumo.iberdrola.es`, are aliases for the same Cloud service. 

```bash
% nslookup datosmonitorconsumo.iberdrola.es
Server:		192.168.2.1
Address:	192.168.2.1#53

Non-authoritative answer:
datosmonitorconsumo.iberdrola.es	canonical name = ingest-prod-iberdrola.wibeee.com.
ingest-prod-iberdrola.wibeee.com	canonical name = prod-alb-iberdrola.eba-kr36u6zt.eu-west-1.elasticbeanstalk.com.
Name:	prod-alb-iberdrola.eba-kr36u6zt.eu-west-1.elasticbeanstalk.com
Address: 54.155.166.163
Name:	prod-alb-iberdrola.eba-kr36u6zt.eu-west-1.elasticbeanstalk.com
Address: 52.211.24.13
Name:	prod-alb-iberdrola.eba-kr36u6zt.eu-west-1.elasticbeanstalk.com
Address: 34.241.154.205
```

You can test that it is working by making the change in the Wibeee device while you have the mobile app open. If it is working then you will continue to get live updates in the app every few seconds while the data passes through HA.

**Comment by antonio-fiol** [comment] 2024-01-10 18:43
Interesting. I will try, but it's using a different port number (80 vs 8080).

**Comment by antonio-fiol** [comment] 2024-01-14 19:40
Testing in progress with "final" configuration (wibeee pointing to HA, HA pointing to Iberdrola, despite being different name and port). So far, so good. HA is updating every few seconds and a second later the app updates too.
I see some weird spikes, but I am not certain they're not real... as they seem like the beginning of a step up. Some compressor/pump (fridge, heating, ...) starting, maybe? They were not visible before, that's for sure.
![image](https://github.com/luuuis/hass_wibeee/assets/23309681/c71b0400-ac73-4c18-b4c8-2592f8ec4f8e)

**Comment by luuuis** [comment] 2024-01-15 12:17
@antonio-fiol that's good. The setup works quite nicely with local push configured.

Regarding the original report, I've recently had the chance to observe the same behaviour in my HA. This was caused by some downtime and there are no measurements for the sensor yet HA shows an assumed state of the last known value.

![History – Home Assistant 2024-01-15 12-05-13](https://github.com/luuuis/hass_wibeee/assets/161006/8cef4491-b69b-4635-86df-8cd0aaefe93f)

The shown sensor is part of Home Assistant core, not a Wibeee, so it seems this is a HA behaviour rather than something in this integration.

I'm sure this worked differently before and that it used to show an empty graph at those points. In any case there is nothing I can do in the integration at this point and therefore I propose closing this issue.

**Comment by antonio-fiol** [comment] 2024-01-15 16:17
Thank you, Luis!

I am pretty sure that the availability of a sensor is something the
integration should be able to report, much like a template sensor now has
an availability parameter.

But I never developed a HA component of any kind, other than writing some
templates, so you know much better.

I haven't seen any gaps since the change, so I don't "care" if we keep it
open or close it. Also, knowing that you can reproduce the behaviour, there
is little more I can do to help anyway.

**Comment by luuuis** [comment] 2024-01-15 18:18
Yes of course @antonio-fiol. Here is where availability is handled in the integration's sensors:

https://github.com/luuuis/hass_wibeee/blob/59e95d20a49caee6d342d4d5f7ba5acf2288486d/custom_components/wibeee/sensor.py#L275-L281

In looking at this code again (to show you) it became apparent that availability is not being handled correctly. This was working previously but it seems I broke it a while back in #39.

This will be fixed shortly. Thank you for bringing it to my attention!

**Closed** 2024-01-15 19:06 UTC
Labels: bug, wibeee wtfs

**Comment by luuuis** [comment] 2024-01-15 19:58
https://github.com/luuuis/hass_wibeee/releases/tag/v3.4.2
