### ISSUE TITLE
Error getting http://xxxxx/en/status.xml

### ISSUE THREAD

**Issue by Abruzzi04** [luuuis/hass_wibeee#43] opened 2022-09-13 19:33 UTC
Este erro teve origem numa integração personalizada.

Logger: custom_components.wibeee.api
Source: custom_components/wibeee/api.py:77 
Integration: wibeee (documentation, issues) 
First occurred: 18:45:26 (2 occurrences) 
Last logged: 19:35:05

Error getting http://xxx.xxx.x.xx/en/status.xml after 3 retries: ClientResponseError: 400, message='Expected HTTP/', url=URL('http://xxx.xxx.1.xx/en/status.xml')

good afternoon… this error is appearing and sometimes the sensor goes to zero.  I've already tried increasing the interval time but it doesn't solve the problem.  I'm not using the API anywhere else and I have the firmware up to date.  Does anyone know what else I can try?  Thanks

**Comment by luuuis** [comment] 2022-09-13 20:53
I explain the cause for this in https://github.com/luuuis/hass_wibeee/issues/11#issuecomment-927860689, it really is a problem with the device firmware becoming unstable when we access its `/en/status.xml` path. One thing that seems to help is to power cycle the device (not just reboot through the UI). What polling interval are you using?

Beginning with [v3.2.0](https://github.com/luuuis/hass_wibeee/releases/tag/v3.2.0), however, there is a better way:
1. Set the polling interval to something high, such as 300 seconds. This will be used to fetch the energy counters.
2. [Configure local push](https://github.com/luuuis/hass_wibeee#configuring-local-push-optional-advanced) to get updates by the second of the instant values (power, voltage, etc).

Once you have this set up the device will never become unstable and you will have instant updates in HA as shown in [[this forum post in HA co](https://community.home-assistant.io/t/new-integration-energy-monitoring-device-circutor-wibeee/45276/257?u=luuuis)](https://community.home-assistant.io/t/new-integration-energy-monitoring-device-circutor-wibeee/45276/255).

Let me know how you go.

**Comment by Abruzzi04** [comment] 2022-09-13 23:01
> I explain the cause for this in [#11 (comment)](https://github.com/luuuis/hass_wibeee/issues/11#issuecomment-927860689), it really is a problem with the device firmware becoming unstable when we access its `/en/status.xml` path. One thing that seems to help is to power cycle the device (not just reboot through the UI). What polling interval are you using?
> 
> Beginning with [v3.2.0](https://github.com/luuuis/hass_wibeee/releases/tag/v3.2.0), however, there is a better way:
> 
> 1. Set the polling interval to something high, such as 300 seconds. This will be used to fetch the energy counters.
> 2. [Configure local push](https://github.com/luuuis/hass_wibeee#configuring-local-push-optional-advanced) to get updates by the second of the instant values (power, voltage, etc).
> 
> Once you have this set up the device will never become unstable and you will have instant updates in HA as shown in [[this forum post in HA co](https://community.home-assistant.io/t/new-integration-energy-monitoring-device-circutor-wibeee/45276/257?u=luuuis)](https://community.home-assistant.io/t/new-integration-energy-monitoring-device-circutor-wibeee/45276/255).
> 
> Let me know how you go.

Thanks for the reply... I tried 15, 17, 30 seconds and it happened all the time.... less often but it happened always...
With the local push everything seems to be ok, but is there a way to change the interval to not be receiving every second?
Thanks

**Comment by luuuis** [comment] 2022-09-14 07:44
> is there a way to change the interval to not be receiving every second?

Not currently. Can you explain the use case you have for that (why you want it)? What sensors are you using and what update frequency would you like?

**Comment by Abruzzi04** [comment] 2022-09-15 08:31
> 2\. [push local](https://github.com/luuuis/hass_wibeee#configuring-local-push-optional-advanced)

configuring the local push I never had values to go to zero, but it continues to give me the error in the logs.

Changing the range was just to not overload the database

THS

**Comment by luuuis** [comment] 2022-09-17 20:50
Right, gotcha. Really that comes down to configuring retention periods and should be handled at [Recorder](https://www.home-assistant.io/integrations/recorder/) level but I will think about how that could be implemented and configured. The device does seem to send the average data once per minute.

Closing this issue since everything is working as expected as far as the integration is concerned.

**Closed by luuuis** 2022-09-17 20:50 UTC
Labels: question, wibeee wtfs

**Comment by Abruzzi04** [comment] 2022-10-04 17:17
Good afternoon. using the "local push" method, Phase 4 does not update along with the other phases. The other phases update by the second, and phase4 updates with the interval of seconds entered in the options. This way my imported and exported energy sensors are very late. Is there a way to resolve this? Thanks

**Comment by luuuis** [comment] 2022-10-04 19:50
@Abruzzi04 please open a new issue and include debug logs as explained in https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting (if you wish to send only the minimum required, the log line that I need to see has the text `receiverLeap` in it).
